### ISSUE TITLE
Asking for location of folder "data/*/*/dp.model.RData"

### ISSUE THREAD

**Issue by nhintruong** [tdhock/PeakSeg-paper#1]
Hi @tdhock, 

I'm working with the dp.peaks.R script to have "dp.peaks.RData" file at the end but I've encountered difficulty locating the 'data' folder referenced in this line:

https://github.com/tdhock/PeakSeg-paper/blob/5ecf869786e18f90f35779a18ff9cb34f6a21428/dp.peaks.R#L4

Could you please guide me on how to find this folder? Thank you for your time and guidance

**Comment by tdhock** [comment]
https://rcdata.nau.edu/genomic-ml/chip-seq-chunk-db/RData.dp.model.txt shows all files available for download, for example https://rcdata.nau.edu/genomic-ml/chip-seq-chunk-db/H3K36me3_AM_immune/10/dp.model.RData

**Comment by tdhock** [comment]
I updated the link on the README https://github.com/tdhock/PeakSeg-paper/commit/9cca421cec6d70fea8779707fd38a564272dec1c
